name: ci-ifcopenshell-conda-daily

on:
  workflow_dispatch:
  schedule:
  #         ┌───────────── minute (0 - 59)
  #         │  ┌───────────── hour (0 - 23)
  #         │  │ ┌───────────── day of the month (1 - 31)
  #         │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  #         │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  #         *  * * * *
  - cron: "49 23 * * *" # 11min before utc midnight every day

jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
      - name: print latest_commit
        run: echo ${{ github.sha }}
      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) &amp;&amp; echo "::set-output name=should_run::false"

  test:
    # if: github.repository == 'IfcOpenShell/IfcOpenShell'
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    name: ${{ matrix.platform.distver }}-${{ matrix.pyver.name }}-${{ matrix.variant }}
    runs-on: ${{ matrix.platform.distver }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        pyver: [
          { name: py311, distver: '3.11'},
          { name: py312, distver: '3.12'}
        ]
        platform: [
          { name: Windows, distver: windows-2022, upload: 'true' },
          { name: Linux, distver: ubuntu-22.04,  upload: 'true' },
          { name: macOS, distver: macos-12, upload: 'true' }
        ]
        variant: [
          'novtk',
#          'all'
        ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Download MacOSX SDK
        if: ${{ matrix.platform.name == 'macOS' }}
        run: |
          curl -o MacOSX10.13.sdk.tar.xz -L https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX10.13.sdk.tar.xz && \
          tar xf MacOSX10.13.sdk.tar.xz && \
          sudo mv -v MacOSX10.13.sdk /opt/ && \
          ls /opt/

      - uses: mamba-org/setup-micromamba@v1 # https://github.com/mamba-org/setup-micromamba
        with:
          environment-name: build-env
          cache-environment: true
          condarc: |
            channels:
              - conda-forge
            channel_priority: strict
          create-args: >-
            python=3.11
            anaconda-client
            boa

      - name: build, test and upload ifcopenshell
        if: ${{ matrix.platform.upload == 'true' }}
        run: |
          conda mambabuild . --python ${{ matrix.pyver.distver }} -c conda-forge --variants "{variant: ${{ matrix.variant }}}" --token ${{ secrets.ANACONDA_TOKEN }} --user ifcopenshell
        working-directory: ./conda
